- README.md
Corrected description `Readme.md`
> TRIVIAL: Update README.md

- src/providers/reader.spec.ts
- src/providers/reader.ts
> ISSUE-15: Fix «dot» option

- src/providers/reader.spec.ts
- src/providers/reader.ts
* #15 
* Mark directory by the final slash.
* Just some refactoring for `reader` tests.
> ISSUE-15: Refactor tests

- README.md
- src/managers/options.spec.ts
- src/managers/options.ts
- src/providers/reader.spec.ts
- src/providers/reader.ts
* #15 
* Ability to skip expanding of symlinked directories
> ISSUE-15: Ability to skip expanding of symlinked directories

- README.md
- src/managers/options.spec.ts
- src/managers/options.ts
- src/providers/reader.spec.ts
- src/providers/reader.ts
* #15
* Add some node-glob compatible options.
> ISSUE-15: Some node-glob compatible options

- package.json
- src/managers/tasks.ts
- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/providers/filters/entry.spec.ts
- src/providers/filters/entry.ts
- src/providers/reader.spec.ts
- src/providers/reader.ts
- src/tests/index.ts
* #15
* Extract filters from reader to avoid large classes.
> ISSUE-15: Extract filters from reader

- src/benchmark/index.ts
- src/benchmark/utils.spec.ts
- src/benchmark/utils.ts
* #15 
* Ability to provide options from env.
> ISSUE-15: Ability to provide options from env

- .npmignore
* #15 
* Exclude «fixtures» directory from package.
> ISSUE-15: Cleanup package

- src/providers/filters/entry.ts
* https://github.com/mrmlnc/fast-glob/issues/46
This is a fix for bug. Now we change original value.
* Dump entry path before work with it.
> ISSUE-46: Dump entry path before work with it

- README.md
- src/managers/tasks.spec.ts
- src/managers/tasks.ts
- src/providers/filters/deep.spec.ts
- src/utils/pattern.spec.ts
- src/utils/pattern.ts
This is a performance improvements for #45.
Allow to excluding directories from reading, when user provide negative patterns with globstar.
> ISSUE-45: Allow to exclude directories with globstar

- package.json
Update `globby` package to `v8.0.0`.
> TRIVIAL: Update «globby» package

- src/adapters/fs-stream.spec.ts
- src/adapters/fs-stream.ts
- src/adapters/fs-sync.spec.ts
- src/adapters/fs-sync.ts
- src/adapters/fs.spec.ts
- src/adapters/fs.ts
- src/providers/reader-async.spec.ts
- src/providers/reader-async.ts
- src/providers/reader-stream.spec.ts
- src/providers/reader-stream.ts
- src/providers/reader-sync.spec.ts
- src/providers/reader-sync.ts
- src/providers/reader.ts
- src/utils/path.spec.ts
- src/utils/path.ts
**Sync**
```
=> Current
node-glob: 88.939ms
fast-glob: 884.304ms
=> Next
node-glob: 55.320ms
fast-glob: 48.016ms
```
* Adapters for reading static patterns in the sync and stream mode.
> ISSUE-60: Time to find a non glob path increase with number of files in the same directory

- README.md
- index.d.ts
- index.js
- src/index.spec.ts
- src/index.ts
* Ability to generate tasks and export it.
* Provide the `generateTasks` function.
> ISSUE-71: Ability to export tasks

- package.json
Just try to avoid  expanding of patterns by shell.
> TRIVIAL: Avoid expanding of patterns by shell

- .travis.yml
- appveyor.yml
The ability to not run the builds twice on the same commit.
Performance? To reduce the use of resources in Travis & AppVeyor?
> TRIVIAL: Prevent double build of the same commit

- .travis.yml
- appveyor.yml
Improve CI experience.
* Enable fast finishing for failed builds
* Automatic release creation on GitHub
* Build & Unit tests & Smoke tests
* The creation of archives for the compiled data.
* Disable the `email` provider for notifications
* Enable `node_modules` cache
> TRIVIAL: Improve CI experience

- .travis.yml
- appveyor.yml
> ISSUE-98: Node.js 10

- src/providers/reader.spec.ts
- src/providers/reader.ts
Fixes https://github.com/mrmlnc/fast-glob/issues/121
*changed order of operations when mixing absolute and markDirectories 
*added tests
> Fixes #121

- src/index.spec.ts
- src/index.ts
Add validation of input data. This is necessary for users from the JS-world.
> ISSUE-119: Add validation of input data

- README.md
- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/tests/smoke/deep.smoke.ts
> ISSUE-129: Fix deep property work

- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/utils/pattern.spec.ts
- src/utils/pattern.ts
This is potential fix for #120.
…
> ISSUE-120: Optimizations for non-globstar patterns

- package.json
- src/adapters/fs.ts
- src/benchmark/reporter.spec.ts
- src/benchmark/utils.spec.ts
- src/index.spec.ts
- src/managers/options.spec.ts
- src/managers/options.ts
- src/managers/tasks.ts
- src/providers/filters/entry.ts
- src/providers/reader-async.spec.ts
- src/providers/reader-async.ts
- src/providers/reader-stream.spec.ts
- src/providers/reader-stream.ts
- src/providers/reader-sync.spec.ts
- src/providers/reader-sync.ts
- src/providers/reader.spec.ts
- src/tests/index.ts
- src/tests/smoke/smoke.ts
- src/utils/pattern.spec.ts
- src/utils/stream.spec.ts
- tslint.json
Stricter rules for code style.
* Update the `tslint-config-mrmlnc` package to 2.0.0
* Fix style issues
> Update "tslint-config-mrmlnc" to 2.0.0

- src/adapters/fs.spec.ts
- src/adapters/fs.ts
- src/providers/filters/deep.spec.ts
- src/providers/filters/entry.spec.ts
- src/providers/reader.spec.ts
- src/tests/index.ts
In yesterday's incident, I discovered that we use different structures in tests and production code. This is the fix for it.
Commits.
> ISSUE-144: Use `fs.Stats` class for tests

- src/tests/smoke/static.smoke.ts
> ISSUE-144: Add smoke test case for output with stats option

- .vsts/build-steps.yml
- .vsts/build.yml
- README.md
- package.json
- src/benchmark/utils.spec.ts
- src/index.ts
This is a fix for issue #151.
* Clarify documentation about return type.
> ISSUE-151: Clarify documentation about return type

- src/benchmark/index.ts
- src/benchmark/reporter.spec.ts
- src/benchmark/reporter.ts
- src/benchmark/runner.spec.ts
- src/benchmark/runner.ts
- src/benchmark/utils.ts
- src/index.spec.ts
- src/index.ts
- src/managers/tasks.spec.ts
- src/managers/tasks.ts
- src/providers/reader-async.spec.ts
- src/providers/reader-async.ts
- src/providers/reader-stream.spec.ts
- src/providers/reader-stream.ts
- src/providers/reader-sync.spec.ts
- src/providers/reader-sync.ts
- src/providers/reader.spec.ts
- src/providers/reader.ts
- src/tests/index.ts
- src/tests/smoke/smoke.ts
- src/types/entries.ts
- tslint.json
> TRIVIAL: drop `I` prefix for interfaces

- src/utils/pattern.spec.ts
- src/utils/pattern.ts
Fix regression after update to `micromatch@4` in #154.
> ISSUE-154: fix regression after update to micromatch@4

- README.md
to improve readme doc
updated the example to be valid
> README update, ignore option takes an array

- README.md
> ISSUE-89: documentation about UNC path

- README.md
> ISSUE-160: Why are parentheses match wrong

- README.md
- src/adapters/fs-stream.ts
- src/adapters/fs-sync.ts
- src/adapters/fs.ts
- src/managers/tasks.spec.ts
- src/managers/tasks.ts
- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/providers/filters/error.spec.ts
- src/providers/filters/error.ts
- src/providers/provider.spec.ts
- src/providers/provider.ts
- src/settings.spec.ts
- src/settings.ts
- src/types/index.ts
This is a first iteration for #155.
> ISSUE-183: Improve UX

- README.md
- src/providers/provider.spec.ts
- src/providers/provider.ts
- src/readers/reader.ts
- src/readers/stream.ts
- src/readers/sync.ts
- src/settings.spec.ts
- src/settings.ts
- src/types/index.ts
This is a fix #106.
* The ability to use custom methods for working with FS.
> ISSUE-106: the ability to use custom methods for working with FS

- README.md
Clarify that this project currently **uses** readdir-enhanced and micromatch.
Every time I read that bullet point it confuses me for a moment. It almost sounds like Streams and Promises replaced readdir-enhanced and micromatch 😅 
Removed a character
> README: Clarify usage of packages in highlights section

- src/providers/stream.ts
Another performance improvement for stream provider. Related to issue #147.
**before**
```
async.js
(TIME) 291.221ms ±4.338% | (MEMORY) 4.648MB ±0.038% | Entries: 5143 | Errors: 0 | Retries: 1
stream.js
(TIME) 402.457ms ±8.461% | (MEMORY) 5.851MB ±0.224% | Entries: 5143 | Errors: 0 | Retries: 1
```
**after**
```
async.js
(TIME) 290.873ms ±3.890% | (MEMORY) 4.734MB ±0.333% | Entries: 5143 | Errors: 0 | Retries: 1
stream.js
(TIME) 294.599ms ±3.623% | (MEMORY) 4.611MB ±0.040% | Entries: 5143 | Errors: 0 | Retries: 1
```
* Switch from `.pipe` (transform/duplex stream) to `.emit` (readable stream). Here we do not need a duplex stream (w/r) — just push the changed value to another readable stream.
> ISSUE-147: another stream performance improvements

- README.md
- src/index.ts
- src/providers/async.spec.ts
- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/providers/provider.spec.ts
- src/providers/provider.ts
- src/providers/stream.spec.ts
- src/providers/sync.spec.ts
- src/providers/sync.ts
- src/providers/transformers/entry.spec.ts
- src/providers/transformers/entry.ts
- src/readers/reader.ts
- src/readers/stream.ts
- src/settings.spec.ts
- src/settings.ts
- src/tests/smoke/smoke.ts
- src/tests/smoke/static.smoke.ts
- src/types/index.ts
- src/utils/stream.spec.ts
- src/utils/stream.ts
This is another part of fixes before the release.
> ISSUE-181: fix some issues

- README.md
- src/benchmark/suites/async/fast-glob-current.ts
- src/index.spec.ts
- src/index.ts
#181
```js
const fg = require('fast-glob'); // → async
```
```ts
import * as fg from 'fast-glob'; // → async
import fg = require('./index'); // → async
import fg from 'fast-glob'; // → error
import * as fg from 'fast-glob'; fg.async // → error
```
> ISSUE-181: Set async method as default method

- README.md
- package.json
- src/settings.ts
#155.
* Description of pattern syntax.
* Full description of all options with examples.
> ISSUE-155: Update documentation

- src/types/index.ts
close #205
to fix the pnpm build: https://github.com/pnpm/pnpm/pull/1875
…
> fix: don't export types from deps

- src/providers/filters/error.spec.ts
- src/providers/filters/error.ts
- src/readers/stream.spec.ts
- src/readers/stream.ts
- src/readers/sync.spec.ts
- src/readers/sync.ts
- src/tests/smoke/errors.smoke.ts
- src/tests/smoke/regular.smoke.ts
- src/tests/smoke/static.smoke.ts
- src/types/index.ts
This is a fix for issue #211.
* Use error filter from `ReaderOptions` instead of custom solution.
> ISSUE-211: do not throw an error for non-exist base directory

- .vsts/benchmark.yml
- .vsts/steps-benchmark.yml
- package.json
- src/benchmark/index.ts
- src/benchmark/runner.spec.ts
- src/benchmark/runner.ts
- src/benchmark/suites/product/async/fast-glob.ts
- src/benchmark/suites/product/async/node-glob.ts
- src/benchmark/suites/product/async/tiny-glob.ts
- src/benchmark/suites/product/stream/fast-glob.ts
- src/benchmark/suites/product/sync/fast-glob.ts
- src/benchmark/suites/product/sync/node-glob.ts
- src/benchmark/suites/regression/async/fast-glob-current.ts
- src/benchmark/suites/regression/async/fast-glob-previous.ts
- src/benchmark/suites/regression/stream/fast-glob-current.ts
- src/benchmark/suites/regression/stream/fast-glob-previous.ts
- src/benchmark/suites/regression/sync/fast-glob-current.ts
- src/benchmark/suites/regression/sync/fast-glob-previous.ts
- src/benchmark/utils.spec.ts
- src/benchmark/utils.ts
To separate the two categories of benchmarks:
* The **product** benchmark is a comparison of performance relative to competitors.
* The **regression** benchmark is a comparison of performance relative to the previous version.
> ISSUE-216: product & regression benchmarks

- README.md
> Update README.md. Fix mistype

- package.json
- src/utils/pattern.spec.ts
- src/utils/pattern.ts
This is a fix for #223.
* Update `glob-pattern` to `5.1.0`;
* Route patterns with escape symbol to dynamic patterns;
> ISSUE-223: route patterns with escape symbol to dynamic patterns

- README.md
- src/index.spec.ts
- src/index.ts
- src/utils/path.spec.ts
- src/utils/path.ts
- src/utils/pattern.ts
This is the functionality that was requested in #158.
1. Polish documentation
2. The `escapePath` method
> ISSUE-158: Introduce the `escapePath` method

- src/index.spec.ts
- src/index.ts
- src/utils/index.ts
- src/utils/string.spec.ts
- src/utils/string.ts
This is a fix for issue #247.
* Adds a check of the input value for an empty string.
> ISSUE-247: improve input data validation

- package.json
- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/providers/matchers/matcher.spec.ts
- src/providers/matchers/matcher.ts
- src/providers/matchers/partial.spec.ts
- src/providers/matchers/partial.ts
- src/tests/index.ts
- src/tests/smoke/regular.smoke.ts
- src/tests/utils/pattern.ts
- src/types/index.ts
- src/utils/array.spec.ts
- src/utils/array.ts
- src/utils/pattern.spec.ts
- src/utils/pattern.ts
This is a fix for #156.
* Introduce the partial matcher.
* Use the partial matcher in deep filter to positive patterns matching.
> ISSUE-156: add partial matcher for deep filter

- src/providers/filters/deep.spec.ts
- src/providers/filters/deep.ts
- src/providers/filters/entry.spec.ts
- src/providers/filters/entry.ts
* Simplify writing unit tests for filters.
* Add missing unit tests for filters.
* Simplify `entries` & `deep` filters.
> ISSUE-259: improve unit tests & simplify filters

- src/tests/smoke/smoke.ts
> build: fix typescript@3.9 compilation

- src/providers/filters/entry.spec.ts
- src/providers/filters/entry.ts
This is a fix for #268.
Add only matched entries to the uniqueness index.
> ISSUE-268: Unique option causes static pattern to fail

- .vsts/benchmark.yml
- .vsts/build.yml
Update Azure Pipelines configuration to the modern VM images & Node.js versions.
> Update Azure Pipelines

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
> TRIVIAL: use node@16 for tests

- README.md
See https://github.com/mrmlnc/fast-glob/issues/300#issuecomment-869154135 comment for more details.
> ISSUE-300: clarification for `followSymbolicLinks` option

- src/managers/tasks.spec.ts
- src/managers/tasks.ts
- src/tests/smoke/regular.smoke.ts
> ISSUE-325: do not ignore negative patterns for patterns outside cwd

- .eslintrc.json
- src/providers/filters/entry.ts
- src/tests/smoke/directories.smoke.ts
- src/tests/smoke/smoke.ts
- src/tests/utils/fs.ts
Addresses #290, #291, #335.
The original fix for the problem was suggested by @Trott in #335. This PR inherits the proposed solution satisfying all tests proposed in #291.
> ISSUE-290: trailing slashes on directories return no results

- src/index.spec.ts
- src/tests/smoke/regular.smoke.ts
Add a failing test for #365 
Added failing test + fixture
> test(regular): add failing test for segment matching

- .github/workflows/benchmark.yml
- .github/workflows/codeql.yml
- .github/workflows/main.yml
> Switch to the native way of stopping previous workflow jobs

- README.md
> ISSUE-381: How much parallelism does this package uses? 

- __snapshots__/regular.e2e.js
- src/providers/filters/entry.spec.ts
- src/providers/filters/entry.ts
- src/tests/e2e/patterns/regular.e2e.ts
Fix #343.
All negative patterns will be applied with the dot option enabled.
> ISSUE-343: Apply negative patterns with dot:true

- README.md
- src/index.spec.ts
- src/index.ts
> ISSUE-397: Provide glob, globSync and globSteam aliases

- package.json
- src/benchmark/suites/product/stream.ts
- src/settings.ts
- build: fix build benchmark files
- fix: cast the ignore field to the array
…
…
> ISSUE-404: fix error for the ignore field misuse

- .github/workflows/main.yml
- package.json
Remove support for outdated versions of runtime.
…
> ISSUE-235: End of Node.js 8 & 10 & 12 & 14 support

- README.md
- package.json
- src/benchmark/suites/regression/async.ts
- src/benchmark/suites/regression/stream.ts
- src/benchmark/suites/regression/sync.ts
- src/readers/reader.spec.ts
- src/tests/e2e/patterns/root.e2e.ts
- src/tests/utils/entry.ts
- src/tests/utils/platform.ts
- src/utils/fs.spec.ts
Update @nodelib/fs.* dependencies and always use modern mode.
…
> ISSUE-371: Update @nodelib/fs.* dependencies

- src/index.ts
- src/managers/tasks.ts
- src/settings.ts
This is a fix for #408. Allow to pass readonly array into public methods.
> ISSUE-408: Allow to pass readonly array into public methods

- src/utils/pattern.spec.ts
- src/utils/pattern.ts
> ISSUE-422: keep escaping after brace expansion

- README.md
> docs: add information about enumerable properties for the fs option

- .github/workflows/benchmark.yml
- herebyfile.mjs
- package.json
- src/benchmark/suites/overhead/async.ts
- src/benchmark/suites/overhead/stream.ts
- src/benchmark/suites/overhead/sync.ts
Evaluation of the overhead introduced by the package logic over the file system introspection package.
…
> ci: introduce overhead benchmark

- README.md
- src/providers/filters/entry.spec.ts
- src/providers/filters/entry.ts
- src/tests/e2e/patterns/root.e2e.ts
- src/tests/utils/entry.ts
> ISSUE-438: Exclude only directories with enabled the `onlyFiles` option
