src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/providers/reader.ts
src/types/patterns.ts
src/utils/path.spec.ts
src/utils/path.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

* #34
So we can make RegExp for each pattern once by micromatch and use them for further matching.  This makes the `fast-glob@2` faster then `fast-glob@1`.

ISSUE-34: Fix micromatch performance

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/reader-async.spec.ts
src/providers/reader-stream.spec.ts
src/providers/reader-sync.spec.ts
src/providers/reader.spec.ts
src/providers/reader.ts
src/utils/array.spec.ts
src/utils/array.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a potential fix for #39.
0. By default `deep` filter returns true.
1. Compute maximum depth of patterns to exclude a deeper directory (`**` === `Infinity`).
2. Delete the `globstar` property from `ITask` interface.

ISSUE-39: Fix deeply reading

---

package.json

* #42 
* #48 
Fix `RangeError: Maximum call stack size exceeded` for synchronous mode with large directories.
Temporary switch to fork branch. A thorough solution will be found in https://github.com/BigstickCarpet/readdir-enhanced/issues/11.

ISSUE-42: RangeError: Maximum call stack size exceeded

---

src/managers/options.spec.ts
src/managers/options.ts

Fix problem when `onlyFiles` option and `onlyDirectories` is enabled in the one time. In this case will be work only the `onlyFiles` option.
…

TRIVIAL: Fix problem when onlyFiles & onlyDirectories options is enabled

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is fix for https://github.com/sindresorhus/globby/issues/70 when globby is broken in the Windows machine.
Convert backslashes to forward slashes in the patterns.

GLOBBY-70: Convert backslashes to forward slashes in the patterns

---

package.json
src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/providers/reader-async.ts
src/providers/reader-stream.ts
src/providers/reader-sync.ts
src/providers/reader.ts

This is a fix for https://github.com/sindresorhus/globby/issues/72 when globby needs git executable on install.
Use `readdir-enhanced` package from my own namespace instead of use GitHub URL, because it's needs git executable on install.

GLOBBY-72: Use «readdir-enhanced» from my own namespace

---

README.md

The main options heading is `options-1`.
Removing everything from the url but the hash fragment makes the link work on both npm and Github.

Fix link to options section

---

package.json
src/utils/pattern.spec.ts

Just update dependencies for fix https://github.com/sindresorhus/globby/issues/74.
* Update `micromatch` version
* Allow minor updates

GLOBBY-74: No match found when pattern contains parentheses

---

README.md
src/managers/options.spec.ts
src/managers/options.ts
src/providers/reader.ts

Ability to use options without double negation.
> Double-negative options is a bad developer experience. It's better to just invert the default.
Related to #54.
* Added additional options without negation.
* Use additional options in the package as inverted value.

ISSUE-54: Change double-negative options

---

package.json
src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/reader-async.spec.ts
src/providers/reader-stream.spec.ts
src/providers/reader-sync.spec.ts
src/providers/reader.spec.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is the first step for #60. The ability to split tasks into two types: static and dynamic.
* **static** – non-dynamic patterns.
* **dynamic** – [`is-glob`](https://github.com/micromatch/is-glob) positive check.
* Utils for separating static and dynamic patterns (based on `is-glob` package).
* Mark tasks by `dynamic: boolean` property.

ISSUE-60: Time to find a non glob path increase with number of files in the same directory

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/tests/smoke/regular.smoke.ts
src/tests/smoke/smoke.ts
src/tests/smoke/static.smoke.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a fix for #69.
* Drop some unnecessary conversion and functions
* Correct application of patterns to the entry

ISSUE-69: Doesn't exclude entries when pattern ends with globstar or includes pattern

---

README.md
src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/tests/smoke/regular.smoke.ts
src/utils/path.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is potential fix for #78 and #80.
Now directories are excluded from reading only if negative pattern affect the depth reading:
* Ends with a `/**`
* Ends with a static pattern (`**/node_modules`)

ISSUE-78, ISSUE-80: Ability to prevent deep reading correctly 

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/tests/smoke/ignore.smoke.ts

Allow to use negative patterns in the `ignore` option.

ISSUE-86: Support negative patterns in the «ignore» option

---

src/providers/reader-async.ts
src/providers/reader-stream.ts
src/providers/reader-sync.ts
src/tests/smoke/regular.smoke.ts
src/tests/smoke/static.smoke.ts

This is fix for https://github.com/mrmlnc/fast-glob/issues/93.
When we work with static patterns, we use the `**` pattern. Unfortunately, this does not cover cases with relative paths. 
We have to work with real patterns.

ISSUE-93: Incorrect filter for static patterns

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

This is fix for #101.
The `!(a|b|c)` pattern is matches anything except one of the given patterns.

ISSUE-101: Incorrect negative pattern detection

---

package.json
src/adapters/fs-stream.spec.ts
src/adapters/fs-stream.ts
src/adapters/fs-sync.spec.ts
src/adapters/fs-sync.ts

This PR introduces `@nodelib/fs.stat` package instead of built-in solution.
* Use the `@nodelib/fs.stat` package.
* Fewer tests (they already exist in the package).

TRIVIAL: Use @nodelib/fs.stat in FS adapter

---

src/managers/tasks.spec.ts
src/managers/tasks.ts

Fix bug related to incorrect ignoring patterns.
Example:
```
var fg = require('fast-glob');
fg('fixtures/first/**/*.md', {ignore: ['fixtures/**/*.md']}).then(console.log)
```
Get result:
```
[ 'fixtures/first/file.md',
'fixtures/first/nested/file.md',
'fixtures/first/nested/directory/file.md' ]
```
Expected result:
```
[]
```
I fixed method `findLocalNegativePatterns` which should not only check that base path of ignore pattern includes base path of source pattern but also vice versa.

fix(ignore): ignore patterns which base path includes in source pattern base path

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/providers/reader.ts
src/tests/smoke/absolute.smoke.ts
src/utils/path.spec.ts
src/utils/path.ts

This is fix for #113.
0. Now we apply all negative patterns to each task.
1. We trying to exclude entries by absolute negative patterns when `absolute` options is enabled (in this case we `resolve` absolute path to the entry and them apply negative patterns).

ISSUE-113: Trying to exclude entries by absolute negative patterns

---

src/index.ts
src/providers/reader-stream.ts
src/utils/stream.spec.ts
src/utils/stream.ts

This is fir fox issue #140.
When reading directories, the readable stream is not closed after
the first error. This is valid behavior because errors can occur while
reading the directory. For example, while reading a directory, another
process can delete it.
* Previously, we could only handle the first error. After the first error,
the process crashed due to an unhandled exception. Now we will absorb
all errors from the readable stream.
* Previously, we did not propagate errors to the merged stream.

FG-140: Correct way to handle all error events for stream mode

---

README.md
src/managers/options.spec.ts
src/managers/options.ts
src/providers/reader.ts

This is a fix for issue #153.
* Remove `nobrace`, `noglobstar`, `noext` and `nocase` options.
* The `extension` option was renamed to `extglob`.

ISSUE-153: remove options with double-negation

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

Setting *strict* option to false will make `is-glob` pattern matching more compatible with `micromatch`, `glob` libraries, which is [mentioned in is-glob docs](https://github.com/micromatch/is-glob#option-strict).
In some cases a valid pattern was not recognised as a glob one, example in linked issue.
Set `is-glob` *strict* option to false.
Fix https://github.com/mrmlnc/fast-glob/issues/174

Set is-glob strict to false to match micromatch/glob behavior 

---

README.md
src/adapters/fs.spec.ts
src/adapters/fs.ts
src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/filters/deep.spec.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/providers/provider.spec.ts
src/providers/provider.ts
src/tests/index.ts
src/tests/smoke/absolute.smoke.ts
src/utils/path.spec.ts
src/utils/path.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

Previously, we replaced separators in patterns to a single form (forward-slashes),
which broke the behavior of user patterns in some cases.
Related to: #155, #163, #173.
After this commit:
* patterns should always be written using forward-slash;
* all paths inside this package use separators in accordance with the operating system;

ISSUE-163: patterns can only use forward-slash as a path separator

---

src/providers/provider.spec.ts
src/providers/provider.ts
src/tests/smoke/absolute.smoke.ts
src/utils/path.spec.ts
src/utils/path.ts

This is a fix for issue #157.
The filepath can include `.` or `..` that must be resolved.

ISSUE-157: always resolve absolute filepath

---

README.md
src/managers/tasks.spec.ts
src/managers/tasks.ts

This is a fix for issue #172.
Always mark each pattern as dynamic when the `case` option is disabled (case-insensitive mode).

ISSUE-172: Always mark patterns as dynamic with case-insensitive mode

---

README.md
package.json
src/adapters/fs-stream.spec.ts
src/adapters/fs-sync.spec.ts
src/adapters/fs.spec.ts
src/adapters/fs.ts
src/providers/async.spec.ts
src/providers/async.ts
src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/filters/entry.ts
src/providers/provider.spec.ts
src/providers/provider.ts
src/providers/stream.spec.ts
src/providers/stream.ts
src/providers/sync.spec.ts
src/providers/sync.ts
src/providers/transformers/entry.spec.ts
src/providers/transformers/entry.ts
src/readers/stream.ts
src/readers/sync.ts
src/tests/index.ts
src/tests/smoke/static.smoke.ts
src/types/index.ts
src/utils/fs.spec.ts
src/utils/fs.ts
src/utils/index.ts

Close issues:  #163, #161, #147
* Use `@nodelib/fs.walk` instead of `@mrmlnc/readdir-enhanced` for crawl file system.

ISSUE-163: Use `@nodelib/fs.walk` instead of `readdir-enhanced`

---

src/utils/stream.spec.ts
src/utils/stream.ts

This is a fix for issue #147.
Multiplexing leads to the creation of a new stream. If the source is one, then there is nothing to multiplex and we do not create additional stream by performance reasons.
**before**
```
(TIME) 359.030ms ±7.080% | (MEMORY) 6.691MB ±0.062% | Entries: 5211 | Errors: 0 | Retries: 1
```
**after**
```
(TIME) 245.260ms ±3.078% | (MEMORY) 5.811MB ±0.037% | Entries: 5211 | Errors: 0 | Retries: 1
```

ISSUE-147: fix stream performance

---

README.md
src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/providers/provider.ts
src/settings.spec.ts
src/settings.ts
src/tests/smoke/base-name-match.ts
src/tests/smoke/case-sensitive-match.smoke.ts
src/tests/smoke/mark-directories.smoke.ts
src/tests/smoke/match-base.smoke.ts

This is a fix for #199.
* Rename `matchBase` → `baseNameMatch`
* Fix `baseNameMatch` option behaviour

ISSUE-199: fix `baseNameMatch` option behaviour

---

README.md

Seems like it hasn't changed from before (should be `true`), after testing it. So I corrected it in the readme.

Fix onlyFiles

---

src/providers/provider.spec.ts
src/providers/provider.ts
src/types/index.ts

This is a preparing for a new version of the picomatch/micromatch package where the `strictSlashes` will be enabled by default.
https://github.com/micromatch/picomatch/issues/21
* Set the `strictSlashes` option to `false`.

PICOMATCH-21: Disable strictSlashes option by default

---

src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/tests/smoke/dot.smoke.ts

This is a fix for #226.
We do not need to try to skip dot directories without applying patterns. The pattern may explicitly includes subdirectories starting with `.`.

ISSUE-226: match dot directories by patterns

---

README.md
package.json
src/index.spec.ts
src/index.ts
src/managers/tasks.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is the functionality that was requested in #105.
Use our own solution instead of `is-glob` package ([passess the original tests with some discression](https://gist.github.com/mrmlnc/c1c0d905ce51481259375245b0f02b80)). Our solution allows you to use some options that affect the match. Most likely, after we understand that the solution works and works well, we will try to join this code with `is-glob` package. I don't know now who uses struct syntax and why.

ISSUE-105: Introduce the `isDynamicPattern` method (alternative for `hasMagic`)

---

src/providers/async.ts
src/providers/stream.spec.ts
src/providers/stream.ts
src/readers/stream.ts
src/utils/stream.spec.ts
src/utils/stream.ts

This is a fix for #239.
When a merged streams receives a close event, the streams from which it was created are destroyed.

ISSUE-239: Destroy source streams when the merged stream is closed 

---

src/providers/filters/deep.ts
src/providers/matchers/matcher.spec.ts
src/providers/matchers/matcher.ts
src/providers/matchers/partial.spec.ts
src/providers/matchers/partial.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

Not the partial matcher has a bug: matcher does not check the previous state for parts of the pattern.
```
patterns: ['a/b/c', 'b/d/c']
match 'a/b' → ok by 'a/b/c'
match 'a/d' → ok by 'b/d/c', but must not be ok
```
* Check the previous state for each part of the filepath.

ISSUE-156: correctly handle multiple patterns

---

package.json

This is a temporary fix for #253.
* Add the `picomatch` package as dependency to avoid problem with outdated `picomatch` version in the `micromatch` package.

ISSUE-253: avoid problem with micromatch

---

src/providers/filters/deep.spec.ts
src/providers/filters/deep.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/utils/path.spec.ts
src/utils/path.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a fix for the second problem from issue #257.
```
regex x 23,178,409 ops/sec ±1.35% (91 runs sampled)
implementation x 154,058,251 ops/sec ±0.53% (92 runs sampled)
startsWith x 13,509,321 ops/sec ±0.42% (90 runs sampled)
startsWith2 x 75,557,551 ops/sec ±8.15% (65 runs sampled))
regex x 8,994,021 ops/sec ±8.46% (54 runs sampled))
implementation x 198,810,564 ops/sec ±13.27% (61 runs sampled)
startsWith x 16,207,750 ops/sec ±12.35% (51 runs sampled)
startsWith2 x 99,489,385 ops/sec ±1.63% (84 runs sampled))
regex x 16,868,716 ops/sec ±2.26% (82 runs sampled)
implementation x 477,864,318 ops/sec ±1.72% (83 runs sampled)
startsWith x 14,659,336 ops/sec ±1.16% (86 runs sampled)
startsWith2 x 158,053,865 ops/sec ±0.61% (94 runs sampled)
regex x 20,893,710 ops/sec ±1.48% (87 runs …
```

ISSUE-257: Fix problem with patterns with leading dot segment

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a fix for #266.
The `scan` method in the `picomatch` dependency returns the `['/lib']` part instead of `['', 'lib']`.

ISSUE-266: Correctly split pattern with a forward slash into parts

---

src/tests/smoke/case-sensitive-match.smoke.ts
src/tests/smoke/regular.smoke.ts
src/tests/smoke/smoke.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a fix for #276.
Correctly handle an empty string in `isDynamicPattern` method.

ISSUE-276: Regression in the new version (3.2.3) when using the caseSensitiveMatch option is disabled

---

src/settings.ts

fix on android
fix `concurrency` minimal value

fix on android

---

src/settings.ts

ISSUE-281: additional comment after PR

---

src/tests/index.ts
src/tests/smoke/case-sensitive-match.smoke.ts
src/tests/smoke/regular.smoke.ts
src/tests/smoke/root.smoke.ts
src/tests/utils/platform.ts

This is related to the issue #277.

ISSUE-277: smoke tests for patterns that starts with the leading slash

---

src/managers/tasks.spec.ts
src/managers/tasks.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a fix for #316 and #310.
Now we do not group patterns to the global task when at least one base directory refers to the parent directory.
Right now we don't support patterns like `{.,..}/../*.md`. We'll leave that for the future due to the complexity of implementation.

ISSUE-316: fix support for mixed base directories

---

package.json
src/benchmark/suites/product/async/fdir.ts
src/benchmark/suites/product/sync/fdir.ts

I've been following this project for a long time. It seems to be getting stronger. Add it to product benchmark.
The fdir has a pretty fast directory tree traversal, but the pattern handling is at a low level:
1. No access to `picomatch` settings.
1. Works quickly only with simple patterns.
So, right now we are only interested in this project from the side of a quick read of the directory tree.

TRIVIAL: add fdir to product benchmark

---

src/index.spec.ts
src/index.ts
src/managers/patterns.spec.ts
src/managers/patterns.ts

Allow to use patterns like `fixtures//*` for consistency with alternative solutions.
Addressed to #330.
In this PR, we introduce a new pattern manager designed to clean up patterns. Right now we just remove duplicated slashes from patterns.

ISSUE-330: double-slash in the middle of the pattern is not collapsed

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

Fix a potential performance cliff in pathological case.
Matching large numbers of repetitions of `[` can take a minute or more in the
current code. This change gets it back down into the milliseconds as
expected.
Instead of matching "open bracket followed by whatever and then a close bracket", this change has the regexp ignore repeated open brackets to avoid polynomial backtracking.

fix: adjust inefficient regular expression

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

Fixes a regex-backtracking performance cliff for some pathological cases.
Replaced `.*` in two places with matching lists `[^(]` and `[^|]`. Wrote tests to confirm performance cliffs in current code and their elimination with this change.

fix: remove performance cliff for regex

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

This is another fix for https://github.com/mrmlnc/fast-glob/pull/338.

Fixing CodeQL alerts

---

package.json
src/managers/patterns.ts

This is a fix addressed to #345.
1. Require node.js 8.6.0. The `micromatch` package works only with node.js 8.6+. This is not a major change, since this version was previously required implicitly.
1. Fix regression from the issue.

ISSUE-345: fix invalid regular expression

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

Fix braces pattern to support more than 2 choices

---

src/utils/pattern.spec.ts
src/utils/pattern.ts

This is a final fix for #351 based on the first regular expression ([click](https://github.com/mrmlnc/fast-glob/blob/eda8195a92e789e9579eb36cfdb7a7639ba3fd8d/src/utils/pattern.ts#L15)).
> Some people, when confronted with a problem, think
> “I know, I'll use regular expressions.”   Now they have two problems.
So, аfter correcting the polynomial explosion ([1](https://github.com/mrmlnc/fast-glob/commit/5669faba60f9e1bfc10542231d9c7d83fc122e65), [2](https://github.com/mrmlnc/fast-glob/commit/92a7fcb35ac031a7c20aa237c0678dfa1139ace8)), we had problems with detecting brace expansion.
I couldn't write a valid regular expression (taking into account the current versions of platform) that would work with the pattern from issue (`abc/{a.txt,b.txt}`), so I rewrote it to a regular function. This …

ISSUE-351: Bash style brace expansions stops working after upgrade to 3.2.8

---

src/tests/smoke/regular.smoke.ts

Add test for bug introduced in 3.2.8: See #357
Added failing test for negative groups

test: add spec for negative groups

---

src/providers/async.spec.ts
src/providers/async.ts
src/readers/async.spec.ts
src/readers/async.ts

Improving the performance of the `fg('**')` method.
Something like ~20% for medium directories and trees. Practically nothing for large directories and trees (1 million and more).
```js
// *
===> Benchmark pattern "*" with 200 launches (regression, async)
===> Max stdev: 7 | Retries: 5 | Options: {}
Name                   Time, ms  Time stdev, %  Memory, MB  Memory stdev, %  Entries  Errors  Retries
---------------------  --------  -------------  ----------  ---------------  -------  ------  -------
fast-glob-current.js   6.970     0.402          4.388       0.014            5        0       1
fast-glob-previous.js  8.571     0.430          4.531       0.015            5        0       1
// **
===> Benchmark pattern "**" with 200 launches (regression, async)
===> Max stdev: 7 | Retries: 5 …
```

perf: use fs.walk instead of fs.walkStream for async provider

---

src/index.ts

For people using ESM projects, assigning to `export = FastGlob` makes default import impossible without TSC interop interceding for it.
Ideally, the export signature should change, but that would be a breaking change.
So for now, and to make the export signature more consistent anyway, I'm proposing just adding the async implementation to the named exports, which happens to also be best-practice for ESM.

Make async available in named export

---

__snapshots__/base-name-match.e2e.js
src/managers/tasks.spec.ts
src/managers/tasks.ts
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/tests/e2e/options/base-name-match.e2e.ts

ISSUE-312: correctly handle patterns without slashes when the `baseNameMatch` option is enabled

---

README.md
src/index.spec.ts
src/index.ts
src/utils/path.spec.ts
src/utils/path.ts

Fix #240.
The main purpose is to allow users to stop processing Windows paths in each location where this package is used, using third-party packages.
The story about automatic pattern conversion is out of the issue now, as it is a separate big layer of problems.
1. The `.escapePath` method now escapes a different set of special characters depending on the platform. Two methods have also been added: `.escapePosixPath`, `.escapeWindowsPath`.
1.1. Added support for escaping an escape character (`\\`) when it is not followed by a special character.
1.2. On Windows, the following characters `*?|[]` will no longer be escaped. Because it is not possible to use these characters in a path in DOS.
2. Added the `.convertPathToPattern` method, which allows you to safely convert DOS paths and UNC …

ISSUE-240: Method to convert path to pattern

---

__snapshots__/unique.e2e.js
src/providers/filters/entry.spec.ts
src/providers/filters/entry.ts
src/tests/e2e/options/unique.e2e.ts
src/tests/e2e/runner.ts

This is a partial fix for #190. This pull request fix duplicate results for overlapping patterns due to a leading dot, as mentioned in https://github.com/mrmlnc/fast-glob/issues/190#issuecomment-502436643.
Do not use `path.normalize` because it is an expensive function in terms of execution time.  For 10_000 entries - 3ms; 100_000 – 10ms; 1_000_000 – 80ms.
```js
// utils.path.removeLeadingDotSegment
fg: 352.983ms
183249
// path.normalize
fg: 493.967ms
183249
```
Uh, oh.
If there are issues on this topic, it will be necessary to consider the possibility of normalizing patterns at the task creation stage.

ISSUE-190: Fix duplicate results for overlapping patterns due to a leading dot

---

src/readers/reader.spec.ts
src/readers/reader.ts
src/readers/stream.ts
src/readers/sync.ts
src/types/index.ts
src/utils/fs.ts

In addition to the changes to @nodelib, use native `fs.Dirent` instead of our own implementation. This is necessary to eliminate the difference between the behavior of Node.js internal modules and this package.

Use native fs.Dirent

---

src/index.ts
src/providers/async.spec.ts
src/providers/async.ts
src/providers/index.ts
src/providers/provider.spec.ts
src/providers/provider.ts
src/providers/stream.spec.ts
src/providers/stream.ts
src/providers/sync.spec.ts
src/providers/sync.ts
src/readers/async.spec.ts
src/readers/async.ts
src/readers/index.ts
src/readers/reader.spec.ts
src/readers/reader.ts
src/readers/stream.spec.ts
src/readers/stream.ts
src/readers/sync.spec.ts
src/readers/sync.ts
src/settings.ts
src/utils/array.spec.ts
src/utils/array.ts

- refactor: rename utils/array/flatten method
- refactor: inject Reader's into Provider's
- fix: use correct value from settings for throwErrorOnBrokenSymbolicLink
- refactor: move CPU count calculation into class
…
…

Minor changes after updating configs

---

src/providers/transformers/entry.spec.ts
src/providers/transformers/entry.ts
src/tests/e2e/options/absolute.e2e.ts
src/utils/path.spec.ts
src/utils/path.ts
src/utils/string.ts

Addressed to several issues: #370, #379.
The main purpose of these changes is to stop casting the path to POSIX style (even on Windows) when the `absolute` option is enabled.
Current cases:
* `test-a@(\\\\)/test.js` (#379)
* #370
…

ISSUE-370: Do not cast the path to POSIX style

---

README.md
__snapshots__/unique.e2e.js
src/benchmark/suites/product/async.ts
src/benchmark/suites/product/stream.ts
src/benchmark/suites/product/sync.ts
src/benchmark/suites/regression/async.ts
src/benchmark/suites/regression/stream.ts
src/benchmark/suites/regression/sync.ts
src/index.spec.ts
src/index.ts
src/tests/e2e/options/unique.e2e.ts
src/tests/e2e/runner.ts

Major release is a good reason to make major changes to the API and indicate the further direction of development.
In this pull request we change the following API's:
1. Remove default method (`fg(…)`);
2. Deprecate `.async`, `.sync` and `.stream` methods in favor of `.glob{,Sync,Stream}`:
Why are we doing this?
In the future, we want to provide package code in a bundle (one `.js` and `.d.ts`). The current toolkit does not work well with namespaces in default imports.
…

ISSUE-371: breaking changes for public api

---

README.md
src/utils/path.spec.ts
src/utils/path.ts

On Windows, you can use square brackets in file paths.
…

fix: escape square braces on Windows platform

---

README.md
src/benchmark/suites/product/async.ts
src/benchmark/suites/product/stream.ts
src/benchmark/suites/regression/async.ts
src/benchmark/suites/regression/stream.ts
src/providers/provider.spec.ts
src/providers/provider.ts
src/settings.spec.ts
src/settings.ts

In most cases, users do not use this option. There are only a couple of places on GitHub right now where users specify concurrency. The value passed there is `os.cpu().length`.
When specifying any value, the concurrency is always limited by the libuv library.
> In Node, there are [two types of threads][nodejs_thread_pool]: Event Loop (code) and a Thread Pool (fs, dns, …). The thread pool size controlled by the `UV_THREADPOOL_SIZE` environment variable. Its default size is 4 ([documentation][libuv_thread_pool]). The pool is one for all tasks within a single Node process.
> 
> Any code can make 4 real concurrent accesses to the file system. The rest of the FS requests will wait in the queue.
> 
> > :book: Each new instance of FG in the same Node process will use the same Thread pool.
> 
> …

Remove the concurrency option

---

README.md

Fix a typo.
There is a redundant `fg.globSync(patterns, [options])` in the readme.

docs: remove redundant example

---

package.json

closes https://github.com/mrmlnc/fast-glob/issues/443
Fix a security vulnerability for `braces`
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-4068
Updated one line in packages.json to point to the fixed versions
https://github.com/micromatch/micromatch/issues/249 
https://github.com/micromatch/braces/issues/35
--> https://github.com/micromatch/braces/releases/tag/3.0.3

update micromatch to address CVE-2024-4068

---

__snapshots__/absolute.e2e.js
package.json
src/providers/filters/entry.ts
src/tests/e2e/options/absolute.e2e.ts
src/utils/pattern.spec.ts
src/utils/pattern.ts

Fixes #441, based on an idea from #445.
Use only absolute (negated) patterns when matching against absolute paths to skip in filter.

ISSUE-441: apply absolute negative patterns to full path

---

package.json

To avoid warnings about GHSA-952p-6rrq-rcjv aka CVE-2024-4067
I am a transitive user of fast-glob, so I figured it'd be nice to fix it here.
I pointed to the next patch release as direct dependency.

package.json: Refer to micromatch 4.0.8+ to address CVE-2024-4067 

---

herebyfile.mjs
package.json
src/benchmark/suites/product/async.ts
src/benchmark/suites/product/sync.ts
src/benchmark/utils.ts
src/tests/e2e/runner.ts
tsconfig.json

First, the `fdir` package is not a glob solution. Yes, it can be used as a glob, but it simply uses `picomatch` to find matching paths and does not apply any heuristics. This is clearly visible in our benchmarks. Rather, it is a competitor to `@nodelib/fs.walk`, not `fast-glob`.
```js
Using ~/work/fast-glob/fast-glob/herebyfile.mjs to run bench:product:async
Starting bench:product:async:flatten
Label              import.time (time)  time (time)       memory (memory)    entries (value)  process.time (time)
-----------------  ------------------  ----------------  -----------------  ---------------  -------------------
async fast-glob *  10.146ms ±2.178%    4.414ms ±1.719%   5.389 MiB ±0.000%  6 ±0.000%        43.573ms ±1.645%   
async node-glob *  14.556ms ±6.243%    6.483ms ±3.063%   5.137 …
```

Add tinyglobby to product benchmark instead of fdir

---

.github/workflows/main.yml
package.json

So, the major version of `fast-glob` has been delayed and it's time to move on with (eslint, @nodelib, mocha, …).
https://nodejs.org/en/blog/announcements/nodejs16-eol#changing-the-end-of-life-date-for-nodejs-16-to-september-11th-2023

Require node@18.18+

---

.github/workflows/codeql.yml

CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3.

ci: update codeql actions

---

src/providers/filters/entry.ts

Optimization of deep directory asynchronous crawls by ~5-10%.
```js
// Without options (~5%)
Label              import.time (time)  time (time)       memory (memory)     entries (value)  process.time (time)
-----------------  ------------------  ----------------  ------------------  ---------------  -------------------
async current **   26.208ms ±3.187%    64.608ms ±2.053%  11.031 MiB ±4.829%  17452 ±0.000%    123.354ms ±2.018%  
async previous **  24.411ms ±3.881%    66.132ms ±4.072%  11.163 MiB ±6.652%  17452 ±0.000%    120.214ms ±2.595% 
// With absolute: true (~10%)
Label              import.time (time)  time (time)        memory (memory)      entries (value)  process.time (time)
-----------------  ------------------  -----------------  -------------------  --------------- …
```

perf: optimizing the patterns set matching by exiting early

---

README.md
src/index.spec.ts
src/providers/provider.spec.ts
src/providers/provider.ts
src/readers/stream.ts
src/settings.spec.ts
src/settings.ts

This is allow to use `AbortSignal` to abort glob progress.
#435
Just passing the `signal` option to `@nodelib/fs.walk`.
https://github.com/nodelib/nodelib/pull/104

Support AbortSignal to abort the processing
